---
title: "HW 4, pt. 1: Programming Exercises"
author: "Julia Du"
output: github_document
---

## Load necessary libraries

```{r}
library(tidyverse)
library(knitr)
library(ggthemes)

theme_set(theme_minimal())

#not relevant - class exercises
mean_mtcars <- vector("numeric", length = ncol(mtcars))
for(i in seq_along(mtcars)) {
  output[[i]] <- mean(mtcars[[i]])
}

max_diamonds <- vector("numeric", length = ncol(diamonds))
for(i in seq_along(diamonds)) {
  output[[i]] <- max(diamonds[[i]])
}
```

## Compute the number of unique values in each column of `iris`

### Using a `for` loop

```{r}
as_tibble(iris)

unique_iris <- vector("numeric", length = ncol(iris)) 
names(unique_iris) <- names(iris)
for(i in seq_along(iris)) {
  unique_iris[[i]] <- length(unique(iris[[i]]))
}
#alternative body is: n_distinct(iris[[i]])

unique_iris
```

### Using a `map` function

```{r}
iris %>%
  map_int(n_distinct)
#alternative is map_int(iris, function(x) length(unique(x)))
```

## Calculate the square of each element in vector `x`

```{r}
x <- seq(from = 30, to = 1)
x
```

### Using a `for` loop

```{r}
squaredx <- vector("numeric", length = length(x)) 
for(i in seq_along(x)) {    #could also use for(i in 1:length(x))
  squaredx[[i]] <- (x[[i]]) ^2
}
squaredx
```

### Using a `map` function

```{r}
x %>%
map_dbl(~(.x)^2) 
#alternative is map_dbl(x, function(x) x^2)
#my tilde in the 2nd line takes the place of function(x) in 3rd line
```

## Write a function to calculate length of sides in a right-triangle using the Pythagorean Theorem

```{r}
#pythagorean
pyth1 <- function(sides) {
  if(length(sides) != 2) {
    stop("provide only 2 values")
  }
   if(!is.numeric(sides)) {
    stop("sides must be numeric") 
  } else if (is.null(sides[a])) {
    sqrt(c**2 - b**2)
  } else if (is.null(sides[b])) {
    sqrt(c**2 - a**2)
  } else if (is.null(sides[c])) {
    sqrt(a**2 + b**2)
  }
}
 
#from Google. https://rpubs.com/avbernat/617275
  pythagorean <- function(triangle) {
  a <- triangle[[1]]
  b <- triangle[[2]]
  c <- triangle[[3]]
  # if(length(triangle) != 2) {
   # stop("provide only 2 values")
  #}
  # if(!is.numeric(triangle)) {
   # stop("sides must be numeric") 
   #}
  if (is.character(a)) {
    side <- sqrt(c**2 - b**2)
  }
  else if (is.character(b)) {
    side <- sqrt(c**2 - a**2)
  }
  else if (is.character(c)) {
    side <- sqrt(a**2 + b**2)
  }
  return(side)
}
  
  
  
  triangle1 = list(2,3, NA)
  
  
  
  
  
  a, b, c){
  #stopifnot(is.numeric(a))
  #stopifnot(missing(a | b | c)) #if_else?
  if(missing(c)) {
   sqrt(a^2 + b^2) 
  } else if(missing(a)) {
    sqrt(c^2 - b^2)
  } else if(missing(b)) {
  sqrt(c^2 - a^2)
  }
}

```

## Session info

```{r}
devtools::session_info()
```


