---
title: "HW 4, pt. 2: Exploring World Bank Data"
author: "Julia Du"
output: github_document
---

## Load necessary libraries

```{r}
library(tidyverse)

#don't do iteration w/in function, dummy!!
mean_mtcars <- vector("numeric", length = ncol(mtcars))
for(i in seq_along(mtcars)) {
  output[[i]] <- mean(mtcars[[i]])
}

max_diamonds <- vector("numeric", length = ncol(diamonds))
for(i in seq_along(diamonds)) {
  output[[i]] <- max(diamonds[[i]])
}
```

## Write a function to import the data files

  I'm interested in the following four variables: 
    
    1. Population growth (annual %) = SP.POP.GROW
    2. Urban population growth (annual %) = SP.URB.GROW
    3. Population density (people per sq. km of land area) = EN.POP.DNST
    4. "Life expectancy at birth, total (years)" = SP.DYN.LE00.IN

```{r}
import_tidydata <- function(file_name) {
 path = "./data_world_bank/"  #why this & not "~/data_world_bank/"
 read_csv(paste0(path, file_name), skip = 4) %>%
   rename(country_name = `Country Name`, country_code = `Country Code`, indicator_name = `Indicator Name`, indicator_code = `Indicator Code`) %>%
   filter(indicator_code %in% c("SP.POP.GROW", "SP.URB.GROW", "EN.POP.DNST", "SP.DYN.LE00.IN")) %>%
   #selecting chosen 4 variables: population growth, urban population growth, population density, & life expectancy at birth. doing it here & not in final select of function so that function runs faster
   select(-c(country_code, indicator_name)) %>%
   pivot_longer(cols = `1960`:`2019`, names_to = "year", values_to = "values") %>%
   pivot_wider(names_from = indicator_code, values_from = values) %>%
   select(-X65)
 }

#This is what I used to check my work while creating the function.
sampledfname <- "API_ABW_DS2_en_csv_v2_1226885.csv"
sampledf <- import_tidydata(sampledfname)
```

## Import the data

```{r}
masterdata <- list.files(path = "./data_world_bank/", pattern = "\\.csv$") %>% #could also write "*.csv"
map(import_tidydata) %>%
  reduce(rbind)
```

## Explore the data
```{r}
focus_data <- masterdata %>%
  filter(country_name %in% c("Japan", "China", "Korea, Rep.")) #focusing analysis on Japan, China, & S. Korea
```

## Session info

```{r}
devtools::session_info()
```


